name = "livepoll"
main = "src/worker/index.js"
compatibility_date = "2025-09-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "livepoll_db"
database_id = "0591afbc-849b-46fd-b286-b00f3a905b93"
migrations_dir = "migrations"
